babeld: adopt to upstream header-style
openwrt-routing/packages pull request #640
Opened 2021-02-01 20:29 UTC by PolynomialDivision

Instead of including the headerfiles that define the structs, we add
the struct definitions to our headerfile.

Fixes warning:

```
ubus.h:67:32: warning: 'struct xroute' declared inside parameter list will not be visible outside of this definition or declaration
 void ubus_notify_xroute(struct xroute *xroute, int kind);
                                ^~~~~~
```

2021-02-01 20:42 UTC, kerneis requested changes
This seems like the wrong fix to me, but maybe because I come from an institutional culture of C++ where we avoid forward declarations and instead include the headers that we use.

@jech: can you shed some light on the pros/cons of those forward-declarations for structs (is it because otherwise you'd end up with dependency loops)?

2021-02-01 21:05 UTC, PolynomialDivision commented
Here is an example of upstream code:
https://github.com/jech/babeld/blob/master/local.h#L23-L25

Since we do not need the size of the structs I think it is fine. I'm also very interested about pros/cons! :)

2021-02-02 14:19 UTC, jech commented
The only hard rule is that I don't use guards (`#ifdef _FOO_H`) around include files, which tend to introduce subtle bugs (it becomes difficult to work out at which point a given include file is being included). The consequence is that I don't `#include""` within `#include""`, since that would require a guard.  I also try to avoid `#include<>` within `#include""`, but I'm not dogmatic about that.

The above implies that header files end up depending on each other.  You may solve the problem either by being careful to include your header files in the right order, or by using forward declarations.  I try to do the former (dependencies between header files), but sometimes it causes either a dependency loop or an explosion in the number of required includes, in which case I use a forward declaration.

In your case, it looks like either approach would do.  The `ubus.h` file is only included in two places, so there's no explosion in the number of includes if you decide on the explicit includes approach, and the `ubus.h` file obviously doesn't need to know about route internals, so a forward declaration is fine.

2021-02-03 20:40 UTC, kerneis commented
Thanks a lot for the details, they make sense (and they are indeed a very different approach from the one I'm used to, with header guards). Let's go with forward declarations.

2021-02-03 20:40 UTC, kerneis approved these changes

2021-02-03 20:41 UTC, kerneis commented
Not merging this right away since there is another pull request, maybe we can review everything and then rebase to make a single package version upgrade.

2021-02-03 21:49 UTC, PolynomialDivision commented
Thanks for the explanations. Sounds reasonable.

I never experienced any issues with include-guards, but I think it is very important to follow the same coding style. :)

2021-02-08 16:34 UTC, kerneis commented
Can you please change the Makefile to switch to auto-incrementing the package version?

2021-02-09 21:51 UTC, merged